
'use strict';
const $=s=>document.querySelector(s);
const ROLES=[{name:'생산자',icon:'🌱',definition:'햇빛을 이용해 스스로 양분을 만드는 생물이에요.',examples:[['sunflower','해바라기'],['tree','나무'],['grass','풀']]},{name:'소비자',icon:'🐇',definition:'다른 생물을 먹어 양분을 얻는 생물이에요.',examples:[['rabbit','토끼'],['deer','사슴'],['frog','청개구리']]},{name:'분해자',icon:'🍄',definition:'죽은 생물이나 배설물을 분해해 양분을 얻는 생물이에요.',examples:[['shiitake','표고버섯'],['breadmold','빵곰팡이'],['bacteria','분해 세균']]}];
const LEVELS={easy:{name:'쉬움',fall:6,interval:1.6,goal:6,pool:5},normal:{name:'보통',fall:4.6,interval:1.1,goal:9,pool:8},hard:{name:'어려움',fall:3.5,interval:.85,goal:12,pool:8}};
const SPECIES=[[["sunflower","해바라기"],["tree","나무"],["grass","풀"],["dandelion","민들레"],["clover","토끼풀"],["pine","소나무"],["rice","벼"],["foxtail","강아지풀"],["reed","갈대"],["lotus","연꽃"],["waterlily","수련"],["duckweed","개구리밥"],["hydrilla","검정말"],["cattail","부들"],["spirogyra","해캄"],["kelp","다시마"],["wakame","미역"],["sawtooth","상수리나무"],["coontail","붕어마름"],["oxalis","괭이밥"],["fleabane","개망초"],["cornus","산수유"],["celandine","애기똥풀"],["closterium","반달말"],["hijiki","톳"],["forsythia","개나리"],["orientaloak","갈참나무"],["ginkgo","은행나무"]],[["rabbit","토끼"],["deer","사슴"],["frog","청개구리"],["butterfly","나비"],["chipmunk","다람쥐"],["snail","달팽이"],["tiger","호랑이"],["vulture","독수리"],["grasshopper","메뚜기"],["sparrow","참새"],["hawk","참매"],["spider","거미"],["bee","꿀벌"],["dragonfly","잠자리"],["ricefish","송사리"],["waterbug","물장군"],["heron","왜가리"],["crab","꽃게"],["snake","누룩뱀"],["mole","두더지"],["greattit","박새"],["caterpillar","애벌레"],["weasel","족제비"],["ant","개미"],["crucian","붕어"],["earthworm","지렁이"],["stagbeetle","사슴벌레"],["pondsnail","우렁이"],["egret","백로"],["bulbul","직박구리"],["firetoad","무당개구리"],["riverSnail","다슬기"],["duck","오리"],["falcon","매"],["seaturtle","바다거북"],["gull","갈매기"],["jellyfish","해파리"],["dolphin","돌고래"],["mackerel","고등어"],["coral","산호"],["stingray","가오리"],["divingbeetle","물방개"]],[["mucor","털곰팡이"],["bacteria","분해 세균"],["shiitake","표고버섯"],["penicillium","푸른곰팡이"],["oyster","느타리버섯"],["button","양송이버섯"],["breadmold","빵곰팡이"],["enoki","팽이버섯"],["woodear","목이버섯"],["turkeytail","구름버섯"],["blackmold","검은곰팡이"]]];
const state={mode:'rounds',segmentCount:0,switchAt:0,switchLeft:0,pendingRole:0,switches:0,level:'easy',round:0,status:'home',elapsed:0,count:0,wrong:0,missed:0,hearts:5,score:0,combo:0,maxCombo:0,items:[],effects:[],spawn:0,sequence:[],lastRole:-1,basket:.5,keys:new Set(),results:[],mistakes:new Map(),feedbackUntil:0,badUntil:0};
const CARD={width:96,height:112,start:-116,span:124};
let width=0,height=0,lastTime=0,soundOn=false,audio=null,pointerId=null;
const field=$('#field'),basket=$('#basket'),dialog=$('#dialog');
field.insertAdjacentHTML('beforeend','<div class="speed-tag" id="speed-tag">속도 ×1.00</div>');
$('.intro p').insertAdjacentHTML('afterend','<p class="rule-note">3라운드로 연습하고, 마라톤 최고점에 도전!</p>');
$('[data-level="easy"] small').textContent='가볍게 도전 · 라운드마다 조금씩 빠르게';
$('[data-level="normal"] small').textContent='빠른 판단 · 연속으로 담아 콤보!';
$('[data-level="hard"] small').textContent='더 빠르고 촘촘하게 · 판단력에 도전';
function speedFactor(){if(state.mode==='marathon')return 1+Math.min(.65,Math.floor(state.elapsed/20)*.05);return 1+state.round*.08+Math.min(.12,Math.floor(state.elapsed/10)*.04);}
function multiplier(){return state.combo>=6?3:state.combo>=3?2:1;}
function totalScore(){if(state.mode==='marathon')return state.score;return state.results.slice(0,state.round).reduce((sum,r)=>sum+r.score,0)+state.score;}
function points(text,x,y,loss=false){const el=document.createElement('span');el.className='point-pop'+(loss?' loss':'');el.textContent=text;el.style.left=Math.max(45,Math.min(width-45,x))+'px';el.style.top=y+'px';field.append(el);state.effects.push({el,until:state.elapsed+1});}
function sound(correct=true){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=correct?660:220;g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2);}catch{}}
$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent=soundOn?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-pressed',soundOn);if(soundOn)sound();};
document.querySelectorAll('.level').forEach(button=>button.onclick=()=>{state.level=button.dataset.level;document.querySelectorAll('.level').forEach(b=>b.setAttribute('aria-pressed',b===button));if(state.mode==='rounds')$('#start').textContent=LEVELS[state.level].name+'으로 시작하기';});
function showDialog(content){state.keys.clear();pointerId=null;$('#overlay').hidden=false;dialog.innerHTML=content;$('#field').inert=true;$('.game-head').inert=true;$('.game-bottom').inert=true;dialog.focus();}
function closeDialog(){$('#overlay').hidden=true;$('#field').inert=false;$('.game-head').inert=false;$('.game-bottom').inert=false;field.focus({preventScroll:true});lastTime=performance.now();}
function resetItems(){state.items.forEach(i=>i.el.remove());state.items=[];state.effects.forEach(e=>e.el.remove());state.effects=[];$('#feedback').hidden=true;basket.classList.remove('good','bad');field.classList.remove('hit','danger');}
function measure(){
 if(!field.clientWidth||!field.clientHeight)return;
 width=field.clientWidth;height=field.clientHeight;
 // Share the same responsive dimensions between drawing and collision geometry.
 CARD.width=Math.round(Math.max(68,Math.min(96,width*.2)));
 CARD.height=Math.round(CARD.width*1.17);CARD.start=-CARD.height-4;CARD.span=CARD.height+12;
 field.style.setProperty('--card-width',CARD.width+'px');
 field.style.setProperty('--card-height',CARD.height+'px');
 field.style.setProperty('--photo-height',Math.round(CARD.width*.78)+'px');
 field.style.setProperty('--card-font',Math.max(12,Math.min(15,CARD.width*.156))+'px');
 renderBasket();state.items.forEach(renderItem);
}
function basketX(){return 54+state.basket*Math.max(0,width-108);}
function renderBasket(){basket.style.transform=`translateX(${basketX()-54}px)`;}
function renderItem(i){i.el.style.transform=`translate(${i.x*(width-CARD.width)}px,${CARD.start+i.y*(height+CARD.span)}px)`;}
function hud(){if(state.mode==='marathon'){marathonHud();return;}$('#hearts').hidden=true;$('.round-dots').hidden=false;$('.progress-track').hidden=false;$('#timer').previousElementSibling.textContent='남은 시간';$('#tip').innerHTML='놓침 −10점 · 오답 −20점<br>다른 역할은 그냥 보내 주세요';const config=LEVELS[state.level];$('#round-label').textContent=`${config.name} · ${state.round+1}/3 라운드`;$('#mission').textContent=ROLES[state.round].name+'를 담으세요!';$('#basket-name').textContent=ROLES[state.round].name;$('#field-label').textContent=`${ROLES[state.round].name}만 ${config.goal}개 담아요`;$('#count').textContent=`${state.count}/${config.goal}`;$('#timer').textContent=Math.max(0,Math.ceil(40-state.elapsed))+'초';$('#timer').style.color=state.elapsed>30?'#a34b24':'';$('#progress').style.width=`${state.count/config.goal*100}%`;$('.progress-track').setAttribute('aria-valuemax',config.goal);$('.progress-track').setAttribute('aria-valuenow',state.count);document.querySelectorAll('.round-dots span').forEach((e,n)=>e.classList.toggle('active',n<=state.round));const heartMarkup='♥'.repeat(state.hearts)+`<span class="empty">${'♡'.repeat(5-state.hearts)}</span>`;if($('#hearts').innerHTML!==heartMarkup)$('#hearts').innerHTML=heartMarkup;$('#hearts').setAttribute('aria-label',`하트 ${state.hearts}개 남음`);$('#score').textContent=totalScore().toLocaleString();$('#combo').textContent=state.combo?`${state.combo} 콤보 · ×${multiplier()}`:'연속 담기 도전!';$('#combo').classList.toggle('hot',state.combo>=3);$('#speed-tag').textContent=`속도 ×${speedFactor().toFixed(2)}`;field.classList.toggle('danger',state.mode==='marathon'&&state.hearts<=2);}
function roundIntro(){state.status='intro';state.count=0;state.wrong=0;state.missed=0;state.hearts=5;state.score=0;state.combo=0;state.maxCombo=0;state.elapsed=0;state.badUntil=0;state.feedbackUntil=0;state.spawn=.8;state.sequence=[];state.lastRole=-1;state.basket=.5;state.mistakes.clear();resetItems();hud();measure();const r=ROLES[state.round];showDialog(`<div class="dialog-icon" aria-hidden="true">${r.icon}</div><div class="eyebrow">${LEVELS[state.level].name} · ${state.round+1}라운드 · 속도 ×${speedFactor().toFixed(2)}</div><h2 id="dialog-title">${r.name}를 담아요</h2><p>${r.definition}</p><div class="examples">${r.examples.map(([e,n])=>`<div class="example"><img src="assets/${e}.jpg" alt="${n}"><small>${n}</small></div>`).join('')}</div><div class="rules"><b>40초 안에 ${LEVELS[state.level].goal}개 담기</b><br>맞는 생물을 놓치면 −10점, 다른 역할을 담으면 −20점. 하트 없이 끝까지 연습해요.<br>연속 3개는 점수 2배, 6개부터는 3배!<br>10초마다, 다음 라운드마다 조금 더 빨라져요.</div><button class="primary" id="begin">도전 시작!</button>`);$('#begin').onclick=()=>{state.status='playing';closeDialog();measure();sound();};}
$('#start').onclick=()=>{if(state.mode==='marathon'){startMarathon();return;}state.round=0;state.results=[];state.mistakes.clear();$('#home').hidden=true;$('#game').hidden=false;roundIntro();};
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function spawn(){if(!state.sequence.length){const others=[0,1,2].filter(n=>n!==state.round);state.sequence=shuffle([state.round,state.round,...others]);}const role=state.sequence.shift();if(!speciesBags[role].length)speciesBags[role]=shuffle([...SPECIES[role]]);const [emoji,name]=speciesBags[role].pop();let x=.04+Math.random()*.92;if(state.items.length){const latest=state.items[state.items.length-1];if(Math.abs(x-latest.x)<.24)x=(latest.x+.48)%1;}const el=document.createElement('div');el.className='falling';el.innerHTML=`<img class="species-photo" src="assets/${emoji}.jpg" alt="${name}" draggable="false"><span class="name">${name}</span>`;$('#fall-layer').append(el);const item={el,role,name,emoji,x,y:0,resolved:false};state.items.push(item);renderItem(item);}
function feedback(message,good){if(!good||state.elapsed>=state.badUntil){$('#feedback').textContent=message;$('#feedback').className='feedback'+(good?'':' bad');$('#feedback').hidden=false;state.feedbackUntil=state.elapsed+(good?1.1:2.1);if(!good)state.badUntil=state.elapsed+1.5;}basket.classList.remove('good','bad');void basket.offsetWidth;basket.classList.add(good?'good':'bad');sound(good);}
function penalty(item,missed){if(state.mode==='marathon'){state.hearts=Math.max(0,state.hearts-1);}state.combo=0;const cost=missed?10:20;state.score=Math.max(0,state.score-cost);state.mistakes.set(item.name,{emoji:item.emoji,role:item.role});if(missed)state.missed++;else state.wrong++;feedback(missed?`${item.name} 놓쳤어요! ${state.mode==='marathon'?'♥ −1 · ':''}−10점`:`${item.name}: ${ROLES[item.role].name}예요! ${state.mode==='marathon'?'♥ −1 · ':''}−20점`,false);points(state.mode==='marathon'?'♥ −1':`−${cost}점`,item.x*(width-CARD.width)+CARD.width/2,height-130,true);field.classList.remove('hit');void field.offsetWidth;field.classList.add('hit');}
function catchItem(item){item.resolved=true;item.el.remove();if(item.role===state.round){state.count++;state.combo++;if(state.mode==='marathon'){state.segmentCount++;}state.maxCombo=Math.max(state.maxCombo,state.combo);const gain=10*multiplier();state.score+=gain;points(`+${gain}`,basketX(),height-135);feedback(state.combo>=3?`${state.combo} 콤보! 점수 ${multiplier()}배 ✨`:`${item.name} 쏙! +${gain}점`,true);}else penalty(item,false);hud();}
function finishRound(){if(state.status!=='playing')return;if(state.mode==='marathon'){finishMarathon();return;}state.status='roundEnd';const complete=state.count>=LEVELS[state.level].goal;const timeBonus=complete?Math.max(0,Math.ceil(40-state.elapsed))*2:0;const heartBonus=0;state.score+=timeBonus+heartBonus;const stars=complete?(state.wrong+state.missed===0?3:state.wrong+state.missed<=2?2:1):0;const result={round:state.round,count:state.count,wrong:state.wrong,missed:state.missed,complete,hearts:state.hearts,score:state.score,maxCombo:state.maxCombo,stars,mistakes:[...state.mistakes]};state.results[state.round]=result;hud();resetItems();const last=state.round===2;showDialog(`<div class="dialog-icon" aria-hidden="true">${complete?'🏆':'⏱️'}</div><div class="eyebrow">${state.round+1}라운드 · ${ROLES[state.round].name}</div><h2 id="dialog-title">${complete?'라운드 클리어!':'시간이 다 됐어요'}</h2><div class="stars" aria-label="별 ${stars}개">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><div class="score-hero">${state.score.toLocaleString()}점</div><div class="score-breakdown">${complete?`시간 보너스 +${timeBonus}<br>`:''}최고 ${state.maxCombo}콤보 · 놓친 생물 ${state.missed}개 · 잘못 담기 ${state.wrong}회</div><div class="result-row"><span>알맞게 담기</span><b>${state.count} / ${LEVELS[state.level].goal}개</b></div>${complete?'':`<p>한 번 더 도전해 볼까요?<br>다음 활동으로 넘어가도 괜찮아요.</p><button class="primary fail-button" id="retry">이 라운드 다시 도전</button>`}<button class="${complete?'primary fail-button':'smallbtn fail-button'}" id="next">${last?'전체 결과 보기':complete?'다음 라운드':'다음 라운드로 넘어가기'}</button>`);if(!complete)$('#retry').onclick=()=>{state.results.length=state.round;roundIntro();};$('#next').onclick=()=>{if(last)showResults();else{state.round++;roundIntro();}};}
function showResults(){state.status='results';const total=state.results.reduce((s,r)=>s+r.score,0),complete=state.results.filter(r=>r.complete).length,stars=state.results.reduce((s,r)=>s+r.stars,0);const mistakes=[...new Map(state.results.flatMap(r=>r.mistakes))].map(([name,v])=>`<div class="review-photo"><img src="assets/${v.emoji}.jpg" alt=""><span>${name} → ${ROLES[v.role].name}</span></div>`).join('');showDialog(`<div class="dialog-icon" aria-hidden="true">${complete===3?'🏆':'🏅'}</div><div class="eyebrow">${LEVELS[state.level].name} · 3개 라운드 도전 완료</div><h2 id="dialog-title">${stars===9?'완벽한 생태 바구니!':complete===3?'세 라운드 모두 클리어!':'생태 바구니 탐험 완료!'}</h2><div class="score-hero">${total.toLocaleString()}점</div><p>모은 별 <b>${stars}/9</b> · 최고 <b>${Math.max(...state.results.map(r=>r.maxCombo))}콤보</b></p><div class="result-list">${state.results.map(r=>`<div class="result-row"><span>${ROLES[r.round].icon} ${ROLES[r.round].name}<br><small>${'★'.repeat(r.stars)}${'☆'.repeat(3-r.stars)} · ${r.count}/${LEVELS[state.level].goal}개</small></span><b>${r.score}점</b></div>`).join('')}</div><div class="result-stats">클리어 ${complete}/3 · 놓침 ${state.results.reduce((s,r)=>s+r.missed,0)}개 · 잘못 담기 ${state.results.reduce((s,r)=>s+r.wrong,0)}회</div>${mistakes?`<div class="review"><b>다시 한번 기억해요</b><br>${mistakes}</div>`:''}<p>다시 도전해서 더 높은 점수를 노려봐요!</p><button class="primary" id="again">같은 난이도로 다시 하기</button><button class="smallbtn" id="choose">다른 난이도 고르기</button>`);$('#again').onclick=()=>{state.round=0;state.results=[];state.mistakes.clear();roundIntro();};$('#choose').onclick=goHome;}
function goHome(){state.status='home';if($('#switch-banner'))$('#switch-banner').hidden=true;resetItems();state.keys.clear();$('#game').hidden=true;$('#home').hidden=false;$('#start').focus();}
function pause(){if(!['playing','switching'].includes(state.status))return;const resumeStatus=state.status;state.status='paused';showDialog('<div class="dialog-icon" aria-hidden="true">🍃</div><h2 id="dialog-title">잠깐 쉬어가요</h2><p>시간도 생물도 잠시 멈췄어요.<br>준비되면 이어서 해봐요.</p><div class="pause-buttons"><button class="primary" id="resume">계속하기</button><button class="smallbtn" id="restart">난이도 선택으로</button></div>');$('#resume').onclick=()=>{state.status=resumeStatus;closeDialog();};$('#restart').onclick=goHome;}
$('#pause').onclick=pause;
function moveTo(clientX){if(state.status!=='playing')return;const rect=field.getBoundingClientRect();state.basket=Math.max(0,Math.min(1,(clientX-rect.left-54)/Math.max(1,width-108)));renderBasket();}
field.addEventListener('pointerdown',e=>{if(state.status!=='playing')return;pointerId=e.pointerId;field.setPointerCapture(e.pointerId);moveTo(e.clientX);});field.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||pointerId===e.pointerId)moveTo(e.clientX);});field.addEventListener('pointerup',()=>pointerId=null);field.addEventListener('pointercancel',()=>pointerId=null);
document.addEventListener('keydown',e=>{if(!$('#overlay').hidden&&!$('#game').hidden&&e.key==='Tab'){const buttons=[...dialog.querySelectorAll('button:not(:disabled),input,select,a[href]')];if(e.shiftKey&&(document.activeElement===buttons[0]||document.activeElement===dialog)){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}return;}if(e.key==='Escape'){if(['playing','switching'].includes(state.status))pause();else if(state.status==='paused')$('#resume').click();return;}if(state.status==='playing'&&['ArrowLeft','ArrowRight','a','d','A','D'].includes(e.key)){e.preventDefault();state.keys.add(e.key.toLowerCase());}});document.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
for(const [id,key]of[['left','ArrowLeft'],['right','ArrowRight']]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{if(state.status!=='playing')return;e.preventDefault();b.setPointerCapture(e.pointerId);state.keys.add(key.toLowerCase());});for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>state.keys.delete(key.toLowerCase()));b.addEventListener('click',e=>{if(e.detail===0&&state.status==='playing'){state.basket=Math.max(0,Math.min(1,state.basket+(id==='left'?-.1:.1)));renderBasket();}});}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{state.keys.clear();pause();});new ResizeObserver(measure).observe(field);
function frame(now){const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;if(state.status==='switching'){tickSwitch(dt);}if(state.status==='playing'){state.elapsed+=dt;if(state.mode==='rounds'&&state.elapsed>=40){finishRound();requestAnimationFrame(frame);return;}const left=state.keys.has('arrowleft')||state.keys.has('a'),right=state.keys.has('arrowright')||state.keys.has('d');state.basket=Math.max(0,Math.min(1,state.basket+((right?1:0)-(left?1:0))*dt*1.35));renderBasket();state.spawn-=dt;const speed=speedFactor();if(state.spawn<=0){spawn();state.spawn=LEVELS[state.level].interval/speed;}for(const item of state.items){const previousBottom=CARD.start+item.y*(height+CARD.span)+CARD.height;item.y+=dt*speed/LEVELS[state.level].fall;const bottom=CARD.start+item.y*(height+CARD.span)+CARD.height;const rim=height-89;const center=item.x*(width-CARD.width)+CARD.width/2;if(previousBottom<rim&&bottom>=rim){if(Math.abs(center-basketX())<53)catchItem(item);else if(item.role===state.round){item.resolved=true;item.el.remove();penalty(item,true);}}if(!item.resolved){if(bottom>height+CARD.height){item.resolved=true;item.el.remove();}else renderItem(item);}if((state.mode==='marathon'?state.hearts<=0:state.count>=LEVELS[state.level].goal))break;}state.items=state.items.filter(i=>!i.resolved);state.effects=state.effects.filter(e=>{if(state.elapsed>=e.until){e.el.remove();return false;}return true;});if(state.elapsed>=state.feedbackUntil)$('#feedback').hidden=true;hud();if((state.mode==='marathon'?state.hearts<=0:state.count>=LEVELS[state.level].goal))finishRound();else if(state.mode==='marathon'&&state.elapsed>=state.switchAt&&state.segmentCount>=3)startSwitch();}requestAnimationFrame(frame);}requestAnimationFrame(frame);

async function preloadPhotos(){const button=$('#start');button.disabled=true;const help=$('.how'),instructions=help.innerHTML;help.textContent='생물 사진을 준비하고 있어요…';try{await Promise.all(SPECIES.flat().map(([id])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=()=>reject(new Error(id));img.src='assets/'+id+'.jpg';})));button.disabled=false;help.innerHTML=instructions;}catch{help.classList.add('photos-error');help.textContent='사진을 불러오지 못했어요. assets 폴더가 함께 있는지 확인한 뒤 새로고침해 주세요.';}}
const speciesBags=[[],[],[]];
preloadPhotos();

let practiceLevel='easy';
function readBest(){try{const n=Number(localStorage.getItem('eco-best-v1'));return Number.isSafeInteger(n)&&n>=0?n:0;}catch{return 0;}}
let bestScore=readBest();
function renderBest(){$('#local-best').textContent=`이 기기 최고 점수 ${bestScore.toLocaleString()}점`;}
try{for(const key of ['eco-player-v1','eco-pending-runs'])localStorage.removeItem(key);}catch{}
$('.footer a').textContent=`생물 사진 ${SPECIES.flat().length}종 · 사진 출처`;
renderBest();
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{
 state.mode=button.dataset.mode;
 const marathon=state.mode==='marathon';
 document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b===button));
 $('.difficulty').hidden=marathon;$('.round-path').hidden=marathon;$('#marathon-setup').hidden=!marathon;
 $('.selection h2').textContent=marathon?'얼마나 오래 담을 수 있을까?':'어떤 난이도로 해볼까요?';
 $('.selection .muted').textContent=marathon?'역할이 바뀌는 끝없는 도전, 내 최고 점수를 넘어 봐요!':'하트 없이, 어떤 난이도든 세 라운드를 모두 즐겨요.';
 $('#start').textContent=marathon?'생태 마라톤 시작':'쉬움으로 시작하기';
 if(!marathon){state.level=practiceLevel;$('#start').textContent=LEVELS[state.level].name+'으로 시작하기';}
});
document.querySelectorAll('.level').forEach(b=>b.addEventListener('click',()=>practiceLevel=state.level));
field.insertAdjacentHTML('beforeend','<div class="switch-banner" id="switch-banner" role="status" hidden><strong id="switch-message"></strong><div class="countdown" id="switch-number"></div><p>카드를 정리하고 새 바구니로 시작해요</p></div>');
function marathonHud(){
 $('#hearts').hidden=false;$('.round-dots').hidden=true;$('.progress-track').hidden=true;
 $('#round-label').textContent=`생태 마라톤 · 바구니 전환 ${state.switches}회`;
 $('#mission').textContent=ROLES[state.round].name+'를 담으세요!';$('#basket-name').textContent=ROLES[state.round].name;
 $('#field-label').textContent=`${ROLES[state.round].name}만 쏙!`;
 $('#count').textContent=state.count+'개';$('#timer').previousElementSibling.textContent='도전 시간';
 $('#timer').textContent=Math.floor(state.elapsed/60)+':'+String(Math.floor(state.elapsed%60)).padStart(2,'0');$('#timer').style.color='';
 $('#hearts').innerHTML='♥'.repeat(state.hearts)+`<span class="empty">${'♡'.repeat(5-state.hearts)}</span>`;
 $('#hearts').setAttribute('aria-label',`하트 ${state.hearts}개 남음`);
 $('#score').textContent=state.score.toLocaleString();$('#combo').textContent=state.combo?`${state.combo} 콤보 · ×${multiplier()}`:'연속 담기 도전!';$('#combo').classList.toggle('hot',state.combo>=3);
 $('#speed-tag').textContent=`속도 ×${speedFactor().toFixed(2)}`;field.classList.toggle('danger',state.hearts<=2);
 $('#tip').innerHTML='놓침·오답은 ♥ −1<br>3콤보 점수 2배 · 6콤보 3배';
}
function startMarathon(){
 state.level='normal';state.round=0;state.results=[];state.segmentCount=0;state.switchAt=15+Math.random()*5;state.switchLeft=0;state.switches=0;
 $('#home').hidden=true;$('#game').hidden=false;roundIntro();
 showDialog(`<div class="dialog-icon">🏃</div><div class="eyebrow">생태 마라톤</div><h2 id="dialog-title">도전 준비!</h2><p>첫 바구니는 <b>생산자</b>예요.<br>시간과 개수 제한 없이 하트 5개로 도전해요.</p><div class="rules">알맞게 3개 이상 담으면, 15~20초 뒤 바구니 전환을 예고해요.<br><b>3초 후 무작위로 다른 역할로 바뀝니다.</b><br>놓침 −10점 · 잘못 담기 −20점 · 둘 다 ♥ −1</div><p>이 기기 최고 점수 <b>${bestScore.toLocaleString()}점</b></p><button class="primary" id="begin">도전 시작!</button><button class="smallbtn" id="cancel-run">돌아가기</button>`);
 $('#cancel-run').onclick=goHome;
 $('#begin').onclick=()=>{state.status='playing';closeDialog();measure();sound();};
}
function startSwitch(){
 state.pendingRole=shuffle([0,1,2].filter(n=>n!==state.round))[0];state.switchLeft=3;state.status='switching';state.keys.clear();resetItems();
 $('#switch-banner').hidden=false;$('#switch-message').textContent=`3초 후 바구니가 ${ROLES[state.pendingRole].name}로 바뀝니다!`;$('#switch-number').textContent='3';sound();
}
function tickSwitch(dt){
 state.switchLeft-=dt;$('#switch-number').textContent=Math.max(1,Math.ceil(state.switchLeft));
 if(state.switchLeft>0)return;
 state.round=state.pendingRole;state.switches++;state.segmentCount=0;state.switchAt=state.elapsed+15+Math.random()*5;state.sequence=[];state.spawn=.8;state.status='playing';$('#switch-banner').hidden=true;hud();sound();
}
function finishMarathon(){
 state.status='marathonEnd';resetItems();$('#switch-banner').hidden=true;
 const isNew=state.score>bestScore;bestScore=Math.max(bestScore,state.score);let stored=true;
 try{localStorage.setItem('eco-best-v1',String(bestScore));}catch{stored=false;}renderBest();
 showDialog(`<div class="dialog-icon">🏆</div><div class="eyebrow">생태 마라톤</div><h2 id="dialog-title">${isNew?'새로운 최고 기록!':'멋진 도전이었어요!'}</h2><div class="score-hero">${state.score.toLocaleString()}점</div><p>${state.count}개 담기 · 최고 ${state.maxCombo}콤보<br>${Math.floor(state.elapsed)}초 도전 · 바구니 ${state.switches}번 전환</p><div class="save-status">이 기기 최고 점수 <b>${bestScore.toLocaleString()}점</b><br><small>${stored?'최고 점수는 이 브라우저에만 저장돼요.':'브라우저 저장이 제한되어 이번 화면에서만 기록을 볼 수 있어요.'}</small></div><button class="primary" id="marathon-again">한 번 더 도전!</button><button class="smallbtn" id="marathon-home">처음으로</button>`);
 $('#marathon-again').onclick=startMarathon;$('#marathon-home').onclick=goHome;
}
